# Shadowrocket: 2026-03-16 20:16:56
[General]
user-agent = Mozilla/5.0 (iPhone; CPU iPhone OS 18_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captivelogin.apple.com
dns-server = 1.1.1.1, 8.8.8.8, 208.67.222.222



[Proxy Group]
HQUY-SYSTEM = select, ULTIMATE-VIP, DIRECT
[Proxy]
# Thay IP và Port mới của bạn vào đây
SOLITUDE-PRX = http, 176.100.37.91, 30397

[Proxy Group]
HQUY-SYSTEM = select, SOLITUDE-PRX, DIRECT

[Rule]
# Giữ nguyên các rule của bạn
DOMAIN-SUFFIX,freefiremobile.com,HQUY-SYSTEM
DOMAIN-KEYWORD,ultimatevn,HQUY-SYSTEM
FINAL,DIRECT

[MITM]
enable = true
hostname = *.freefiremobile.com, *.garenanow.com, *.garena.com
# LƯU Ý: Không dán ca-p12 vào đây nếu bạn cài cert thủ công ngoài máy
