[General]
hijack-dns = 8.8.8.8, 1.1.1.1
always-real-ip = com.dts.freefireth, com.dts.freefiremax

[Host]
ultraaim = server:85.31.54.36

[Script]
# Sử dụng code hack trực tiếp để không cần file .js riêng lẻ
FF_VIP = type=http-response,pattern=^https?:\/\/.*freefire.*\.com,requires-body=true,script-path=https://raw.githubusercontent.com/maihoangquy2003-wq/ff-neon/main/index.html
