[General]
# Đây là dòng lừa Server nó rằng bạn dùng máy khác
user-agent = Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X)
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local

[Proxy]
# Dán cái IP và Port của bọn nó vào đây
SERVER-MOD-VIP = socks5, 159.75.183.142, 10110

[Proxy Group]
# Tạo mục chọn ngoài màn hình chính
HQUY-SYSTEM = select, SERVER-MOD-VIP, DIRECT

[Rule]
# Chỉ cho game đi qua Proxy để lấy Aim, còn lại đi thẳng để không lộ dữ liệu khác
DOMAIN-SUFFIX,freefiremobile.com,HQUY-SYSTEM
FINAL,DIRECT
