[General]
hijack-dns = 8.8.8.8, 1.1.1.1
always-real-ip = com.dts.freefireth, com.dts.freefiremax

[Proxy]
# Đã thay IP VPS 85.31.54.36 của bạn vào đây
Ultra-Server = socks5, 85.31.54.36, 41263

[Proxy Group]
# Chọn máy chủ này làm mặc định
Default = select, Ultra-Server

[Script]
# Trỏ thẳng về file data.txt để lấy mã Aim/Antena
FF_VIP = type=http-response,pattern=^https?:\/\/.*freefire.*\.com,requires-body=true,script-path=https://raw.githubusercontent.com/maihoangquy2003-wq/ff-neon/main/data.txt

[MITM]
enable = true
hostname = *.freefireth.com, *.freefiremax.com, raw.githubusercontent.com, ultraaim
