# Shadowrocket: 2026-03-19 17:51:46
[General]
user-agent = Mozilla/5.0 (iPhone; CPU iPhone OS 18_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captivelogin.apple.com
dns-server = 1.1.1.1, 8.8.8.8, 208.67.222.222
update-url = https://raw.githubusercontent.com/maihoangquy2003-wq/ff-neon/main/no_antena.conf

[Proxy]
SOLITUDE-TA-NO-ANTENA = http, 2.56.246.128, 30274

[Proxy Group]
HQUY-SYSTEM = select, SOLITUDE-TA-NO-ANTENA, DIRECT

[Rule]
DOMAIN-SUFFIX,freefiremobile.com,HQUY-SYSTEM
DOMAIN-KEYWORD,ultimatevn,HQUY-SYSTEM
DOMAIN-SUFFIX,github.io,DIRECT
DOMAIN-SUFFIX,githubusercontent.com,DIRECT
FINAL,DIRECT

[Script]
# Đã loại bỏ Script Antena để đảm bảo No Antena hoạt động chuẩn

[MITM]
enable = true
hostname = *.freefiremobile.com, *.ultimatevn.click, *.ultimatevn.pro
ca-passphrase = HTbfsRi4
ca-p12 = 
