[General/*
 * SOLITUDE NEON DASHBOARD
 * Hiển thị bảng thông báo khi vào game
 */

const githubUrl = "https://raw.githubusercontent.com/maihoangquy2003-wq/ff-neon/main/antena.json";

$httpClient.get(githubUrl, function(error, response, data) {
    if (error) {
        $notification.post("Solitude Error", "Không thể kết nối Server!", "");
        $done({});
    } else {
        let obj = JSON.parse(data);
        let users = obj.users;
        
        // UID cố định để test vì bạn chưa soi được UID thực trong Body
        let myID = "8630164412"; 
        
        if (users[myID]) {
            let expiry = users[myID].expiry;
            // Hiển thị thông báo Neon trên màn hình iPhone
            $notification.post("✅ SOLITUDE AUTHORIZED", "Chào mừng: " + myID, "Hạn dùng: " + expiry);
            $done({});
        } else {
            $notification.post("❌ SOLITUDE DENIED", "UID không hợp lệ!", "Vui lòng liên hệ Admin.");
            // Trả về lỗi 500 để chặn không cho vào game
            $done({ status: "HTTP/1.1 500 Internal Server Error" });
        }
    }
});
